spring.application.name=exemplo2-spring-boot-turmaB

# Define o driver do banco de dados 
# (vem configurado por padrão ao importar a dependência) 
spring.datasource.driver-class-name=org.h2.Driver

# URL de conexão do banco de dados
spring.datasource.url=jdbc:h2:mem:bancoteste
# Define o usuário padrão do banco (padrão = sa)
spring.datasource.username=sa
# Define a senha do usuário padrão (vazia por padrão)
spring.datasource.password=

# Habilita o console do H2 (padrão = true)
spring.h2.console.enable=true
# Define a URL do console (padrão = /h2-console)
spring.h2.console.path=/h2-console

# Para o H2 funcionar no codespaces
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework

# Configura o JPA para atualizar a estrutura do banco 
# automaticamente baseado nas classes do Java
# (none: O Hibernate não faz nenhuma operação no esquema do banco) 
# (update: O Hibernate atualiza o esquema criando tabelas ou colunas que faltam)
 spring.jpa.hibernate.ddl-auto=update
